# Generated by Django 3.0 on 2019-12-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=20, verbose_name='학번')),
                ('s_name', models.CharField(max_length=20, verbose_name='이름')),
                ('lecture', models.CharField(max_length=20, verbose_name='과목')),
                ('mid_term', models.IntegerField(default=0, verbose_name='중간고사 점수')),
                ('final_term', models.IntegerField(default=0, verbose_name='기말고사 점수')),
                ('year', models.CharField(max_length=20, verbose_name='년도')),
                ('semester', models.CharField(max_length=20, verbose_name='학기')),
            ],
        ),
    ]
